FROM python:3.12-slim
WORKDIR /app
COPY dxemb/web/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY dxemb ./dxemb
CMD ["gunicorn", "-w", "2", "-b", "0.0.0.0:5000", "dxemb.web.app:app"]
